language: node_js
node_js:  
  - 8
cache:
  directories:
  - node_modules
  - packages/create-react-app/node_modules
  - packages/react-scripts/node_modules
install: true
script:
- 'yarn'  
- 'yarn test'  
env:
  global:
    - USE_YARN=yes  
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN 
  on:
    branch: travis