language: node_js
node_js:
  - 6
  - 8
cache:
  directories:
  - node_modules
  - packages/create-react-app/node_modules
  - packages/react-scripts/node_modules
install: true
script:
- 'yarn'  
- 'yarn test'  
env:
  global:
    - USE_YARN=yes  